import type { DocBlock, DocText, DocumentModel, DocumentSection } from '@/types/document'
import { plainText, toSpans } from '@/features/documents/lib/blocks'

/**
 * Markdown renderer.
 *
 * Targets GitHub-flavoured Markdown, which is the dialect Obsidian, Notion's
 * importer and every LLM chat window understand. Tables use pipe syntax and
 * callouts use GitHub alerts, both of which degrade to readable plain text
 * anywhere they are not supported.
 */

/** GitHub alert keywords, in callout-tone order. */
const ALERT_KEYWORDS: Record<string, string> = {
  info: 'NOTE',
  success: 'TIP',
  warning: 'WARNING',
  risk: 'CAUTION',
  future: 'IMPORTANT',
}

export function exportMarkdown(model: DocumentModel): Blob {
  return new Blob([renderMarkdown(model)], { type: 'text/markdown;charset=utf-8' })
}

export function renderMarkdown(model: DocumentModel): string {
  const parts: string[] = []

  if (model.options.includeCover) parts.push(renderFrontMatter(model), renderCover(model))
  if (model.options.includeDocumentInfo) parts.push(renderDocumentInfo(model))
  if (model.options.includeToc) parts.push(renderToc(model))

  for (const section of model.sections) parts.push(renderSection(section))

  if (model.options.footers) parts.push(renderFooter(model))

  return `${parts.filter(Boolean).join('\n\n')}\n`
}

/* -------------------------------------------------------------------------- */
/* Front matter                                                                */
/* -------------------------------------------------------------------------- */

/** YAML front matter — Obsidian and most static site generators read it. */
function renderFrontMatter(model: DocumentModel): string {
  const entries: Array<[string, string]> = [
    ['title', model.meta.documentTitle],
    ['project', model.meta.projectName],
    ['client', model.cover.client],
    ['version', model.meta.version],
    ['status', model.cover.status],
    ['prepared_by', model.meta.preparedBy || 'Not recorded'],
    ['date', model.meta.generatedDate],
    ['generator', 'ReqStudio'],
  ]

  const lines = entries.map(([key, value]) => `${key}: ${yamlValue(value)}`)
  return `---\n${lines.join('\n')}\n---`
}

function yamlValue(value: string): string {
  const clean = value.replace(/\r?\n/g, ' ').trim()
  return /[:#\-[\]{}&*!|>'"%@`]/.test(clean) ? `"${clean.replace(/"/g, '\\"')}"` : clean
}

function renderCover(model: DocumentModel): string {
  return [
    `# ${model.cover.title}`,
    '',
    `> ${model.cover.subtitle}`,
    '',
    `**${model.cover.projectName}** · ${model.cover.client} · ${model.cover.version} · ${model.cover.status}`,
  ].join('\n')
}

function renderDocumentInfo(model: DocumentModel): string {
  const rows = model.documentInfo.map((item) => {
    const value = item.bullets
      ? item.bullets.map(plainText).join(', ')
      : plainText(item.value)
    return `| ${escapeCell(item.label)} | ${escapeCell(value)} |`
  })

  return ['## Document Information', '', '| Field | Value |', '| --- | --- |', ...rows].join('\n')
}

function renderToc(model: DocumentModel): string {
  const entries = model.sections.map((section) => {
    const indent = section.level === 2 ? '  ' : ''
    const label = `${section.number}. ${section.title}`
    return `${indent}- [${label}](#${slugify(`${section.number} ${section.title}`)})`
  })

  return ['## Contents', '', ...entries].join('\n')
}

function renderFooter(model: DocumentModel): string {
  return [
    '---',
    '',
    `_${model.meta.footerText}_`,
    '',
    `_${model.meta.documentTitle} · ${model.meta.version} · ${model.meta.generatedDate} · Generated by ReqStudio_`,
  ].join('\n')
}

/* -------------------------------------------------------------------------- */
/* Sections                                                                    */
/* -------------------------------------------------------------------------- */

function renderSection(section: DocumentSection): string {
  const hashes = section.level === 1 ? '##' : '###'
  const parts = [`${hashes} ${section.number}. ${section.title}`]

  if (section.description) parts.push('', `_${section.description}_`)

  for (const block of section.blocks) {
    const rendered = renderBlock(block)
    if (rendered) parts.push('', rendered)
  }

  return parts.join('\n')
}

function renderBlock(block: DocBlock): string {
  switch (block.type) {
    case 'heading':
      return `${block.level === 3 ? '####' : '#####'} ${block.text}`

    case 'paragraph':
      return inline(block.text)

    case 'list':
      return block.items
        .map((item, index) => `${block.ordered ? `${index + 1}.` : '-'} ${inlineSingleLine(item)}`)
        .join('\n')

    case 'fields':
      return block.items
        .map((item) => {
          if (item.bullets) {
            const nested = item.bullets.map((bullet) => `  - ${inlineSingleLine(bullet)}`)
            return [`- **${item.label}**`, ...nested].join('\n')
          }
          return `- **${item.label}:** ${inlineSingleLine(item.value)}`
        })
        .join('\n')

    case 'table':
      return renderTable(block)

    case 'callout': {
      const keyword = ALERT_KEYWORDS[block.tone] ?? 'NOTE'
      const body = [block.title ? `**${block.title}**` : '', inlineSingleLine(block.text)]
        .filter(Boolean)
        .join('  \n> ')
      return `> [!${keyword}]\n> ${body}`
    }

    case 'divider':
    case 'pageBreak':
      return '---'

    case 'empty':
      return `_${block.text}_`
  }
}

function renderTable(block: Extract<DocBlock, { type: 'table' }>): string {
  const header = `| ${block.columns.map((column) => escapeCell(column.header)).join(' | ')} |`
  const divider = `| ${block.columns
    .map((column) => (column.align === 'right' ? '---:' : '---'))
    .join(' | ')} |`
  const rows = block.rows.map(
    (row) => `| ${row.map((cell) => escapeCell(plainText(cell))).join(' | ')} |`,
  )

  const table = [header, divider, ...rows].join('\n')
  return block.caption ? `**${block.caption}**\n\n${table}` : table
}

/* -------------------------------------------------------------------------- */
/* Text                                                                        */
/* -------------------------------------------------------------------------- */

function inline(text: DocText): string {
  if (typeof text === 'string') return escapeMarkdown(text)
  return toSpans(text)
    .map((span) => {
      let value = escapeMarkdown(span.text)
      if (span.bold) value = `**${value}**`
      if (span.italic) value = `_${value}_`
      if (span.href) value = `[${value}](${span.href})`
      return value
    })
    .join('')
}

/** Values inside list items and table cells cannot contain hard line breaks. */
function inlineSingleLine(text: DocText): string {
  return inline(text).replace(/\r?\n+/g, '  \n  ')
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n+/g, '<br>').trim()
}

/**
 * Escapes only the characters that would change the structure of the output.
 * Over-escaping makes the source unreadable, which defeats the point of
 * Markdown as a hand-editable format.
 */
function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]<>])/g, '\\$1')
}

/** GitHub's heading-anchor algorithm, closely enough for internal links. */
function slugify(value: string): string {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
}
