import { FileText } from 'lucide-react'
import type { SectionDefinition } from '@/types/section'

export const projectOverviewSection: SectionDefinition = {
  id: 'project-overview',
  order: 1,
  title: 'Project Overview',
  description: 'The elevator pitch: what is being built, why now, and what sits outside the work.',
  icon: FileText,
  weight: 1.2,
  fields: [
    {
      kind: 'textarea',
      name: 'summary',
      label: 'Executive summary',
      placeholder: 'In two or three sentences, what is this project?',
      help: 'Written for a stakeholder who has five seconds to understand the work.',
      required: true,
      rows: 3,
      span: 2,
      maxLength: 1200,
    },
    {
      kind: 'textarea',
      name: 'background',
      label: 'Background & context',
      placeholder: 'What led to this project? Previous attempts, research, or triggering events.',
      rows: 4,
      span: 2,
    },
    {
      kind: 'textarea',
      name: 'problemStatement',
      label: 'Problem statement',
      placeholder: 'What problem are we solving, and for whom?',
      required: true,
      rows: 3,
      span: 2,
    },
    {
      kind: 'list',
      name: 'objectives',
      label: 'Project objectives',
      itemLabel: 'Objective',
      placeholder: 'e.g. Reduce time-to-quote from 5 days to 1 day',
      help: 'Outcome-focused, not feature-focused.',
      required: true,
      minItems: 1,
      span: 2,
    },
    {
      kind: 'list',
      name: 'inScope',
      label: 'In scope',
      itemLabel: 'Scope item',
      placeholder: 'e.g. Public marketing site (12 templates)',
      required: true,
    },
    {
      kind: 'list',
      name: 'outOfScope',
      label: 'Out of scope',
      itemLabel: 'Exclusion',
      placeholder: 'e.g. CRM migration',
      help: 'The cheapest scope control you will ever write.',
    },
    {
      kind: 'list',
      name: 'successCriteria',
      label: 'Definition of success',
      itemLabel: 'Criterion',
      placeholder: 'e.g. Lighthouse performance ≥ 90 on all templates',
      span: 2,
    },
    {
      kind: 'textarea',
      name: 'budgetNotes',
      label: 'Budget & commercial notes',
      placeholder: 'Range, billing model, purchase order references.',
      rows: 2,
      scored: false,
      span: 2,
    },
  ],
}
