import { Server } from 'lucide-react'
import type { SectionDefinition } from '@/types/section'

export const technicalRequirementsSection: SectionDefinition = {
  id: 'technical-requirements',
  order: 8,
  title: 'Technical Requirements',
  description: 'Platform, hosting, performance, security and compliance expectations.',
  icon: Server,
  fields: [
    {
      kind: 'text',
      name: 'platform',
      label: 'Platform / framework',
      placeholder: 'e.g. Next.js on Vercel',
      required: true,
    },
    {
      kind: 'text',
      name: 'cms',
      label: 'CMS',
      placeholder: 'e.g. Sanity, WordPress, none',
      required: true,
    },
    { kind: 'text', name: 'hosting', label: 'Hosting & environments', placeholder: 'e.g. Vercel — dev, staging, prod' },
    { kind: 'text', name: 'domain', label: 'Domain & DNS owner', placeholder: 'Who controls the DNS?' },
    {
      kind: 'multiselect',
      name: 'browsers',
      label: 'Supported browsers',
      options: [
        { value: 'chrome', label: 'Chrome' },
        { value: 'safari', label: 'Safari' },
        { value: 'firefox', label: 'Firefox' },
        { value: 'edge', label: 'Edge' },
        { value: 'samsung', label: 'Samsung Internet' },
      ],
      required: true,
    },
    {
      kind: 'multiselect',
      name: 'devices',
      label: 'Supported devices',
      options: [
        { value: 'desktop', label: 'Desktop' },
        { value: 'tablet', label: 'Tablet' },
        { value: 'mobile', label: 'Mobile' },
      ],
      required: true,
    },
    {
      kind: 'select',
      name: 'accessibilityStandard',
      label: 'Accessibility standard',
      required: true,
      options: [
        { value: 'wcag-2.1-a', label: 'WCAG 2.1 Level A' },
        { value: 'wcag-2.1-aa', label: 'WCAG 2.1 Level AA' },
        { value: 'wcag-2.2-aa', label: 'WCAG 2.2 Level AA' },
        { value: 'wcag-2.2-aaa', label: 'WCAG 2.2 Level AAA' },
      ],
    },
    {
      kind: 'textarea',
      name: 'performanceTargets',
      label: 'Performance targets',
      placeholder: 'e.g. LCP < 2.5s, CLS < 0.1, total page weight < 1 MB',
      rows: 2,
      span: 2,
    },
    {
      kind: 'textarea',
      name: 'securityRequirements',
      label: 'Security requirements',
      placeholder: 'Authentication, data handling, penetration testing, CSP.',
      rows: 2,
      span: 2,
    },
    {
      kind: 'textarea',
      name: 'seoRequirements',
      label: 'SEO requirements',
      placeholder: 'Structured data, canonical rules, redirect strategy, sitemap.',
      rows: 2,
      span: 2,
    },
    {
      kind: 'textarea',
      name: 'analyticsRequirements',
      label: 'Analytics & tracking',
      placeholder: 'Tooling, events, consent management.',
      rows: 2,
      span: 2,
    },
    {
      kind: 'list',
      name: 'integrations',
      label: 'Technical integrations',
      itemLabel: 'Integration',
      placeholder: 'e.g. Salesforce API, Stripe',
    },
    {
      kind: 'list',
      name: 'compliance',
      label: 'Compliance obligations',
      itemLabel: 'Obligation',
      placeholder: 'e.g. GDPR, PCI-DSS, WCAG procurement clause',
    },
    {
      kind: 'textarea',
      name: 'technicalConstraints',
      label: 'Technical constraints',
      placeholder: 'Legacy systems, mandated vendors, network restrictions.',
      rows: 2,
      span: 2,
      scored: false,
    },
  ],
}
