import type { DocBlock, DocText, DocumentModel, DocumentSection } from '@/types/document'
import { toSpans } from '@/features/documents/lib/blocks'
import { htmlShell } from './template'

/**
 * Standalone HTML renderer.
 *
 * Produces one self-contained file — semantic markup, inlined styles, no
 * external requests — that reads well on screen and prints sensibly.
 */

export function exportHtml(model: DocumentModel): Blob {
  return new Blob([renderHtml(model)], { type: 'text/html;charset=utf-8' })
}

export function renderHtml(model: DocumentModel): string {
  const parts: string[] = []

  if (model.options.headers) parts.push(renderHeader(model))
  if (model.options.includeCover) parts.push(renderCover(model))
  if (model.options.includeDocumentInfo) parts.push(renderDocumentInfo(model))
  if (model.options.includeToc) parts.push(renderToc(model))

  parts.push(
    `<main class="body">${model.sections.map(renderSection).join('')}</main>`,
  )

  if (model.options.footers) parts.push(renderFooter(model))

  return htmlShell({
    title: escape(model.meta.documentTitle),
    description: escape(model.cover.subtitle),
    body: `<article class="doc">${parts.join('')}</article>`,
  })
}

/* -------------------------------------------------------------------------- */
/* Furniture                                                                   */
/* -------------------------------------------------------------------------- */

function renderHeader(model: DocumentModel): string {
  return `<header class="doc-header">
<span><strong>${escape(model.meta.projectName)}</strong></span>
<span class="version">${escape(model.meta.version)}</span>
</header>`
}

function renderFooter(model: DocumentModel): string {
  return `<footer class="doc-footer">
<span>${escape(model.meta.footerText)}</span>
<span>${escape(model.meta.generatedDate)} · ${model.statistics.pages} ${model.statistics.pages === 1 ? 'page' : 'pages'} · Generated by ReqStudio</span>
</footer>`
}

function renderCover(model: DocumentModel): string {
  const { cover } = model

  const facts: Array<[string, string]> = [
    ['Project', cover.projectName],
    ['Client', cover.client],
    ['Organisation', cover.organisation],
    ['Project type', cover.projectType],
    ['Prepared by', cover.designer],
    ['Prepared', cover.preparedDate],
    ['Version', cover.version],
    ['Status', cover.status],
  ]

  return `<section class="cover">
<div class="cover-top">
<div class="cover-brand">
<div class="cover-mark" aria-hidden="true">${escape(cover.logoText)}</div>
<div>
<p class="name">${escape(cover.organisation !== 'Not recorded' ? cover.organisation : 'ReqStudio')}</p>
<p class="kind">Requirements documentation</p>
</div>
</div>
<div class="cover-meta">
<p class="version">${escape(cover.version)}</p>
<p>${escape(cover.status)}</p>
</div>
</div>

<div class="cover-title">
<p class="cover-eyebrow">Project requirements brief</p>
<h1>${escape(cover.title)}</h1>
<p class="cover-subtitle">${escape(cover.subtitle)}</p>
<div class="cover-rule" aria-hidden="true"></div>
</div>

<dl class="cover-facts">
${facts.map(([label, value]) => `<div><dt>${escape(label)}</dt><dd>${escape(value)}</dd></div>`).join('')}
</dl>
</section>`
}

function renderDocumentInfo(model: DocumentModel): string {
  const rows = model.documentInfo
    .map((item) => {
      const value = item.bullets
        ? `<ul>${item.bullets.map((bullet) => `<li>${inline(bullet)}</li>`).join('')}</ul>`
        : inline(item.value)
      return `<div><dt>${escape(item.label)}</dt><dd>${value}</dd></div>`
    })
    .join('')

  return `<section class="page" id="document-information">
<h2>Document Information</h2>
<dl class="fields" style="margin-top:1.5rem">${rows}</dl>
</section>`
}

function renderToc(model: DocumentModel): string {
  const entries = model.sections
    .map(
      (section) => `<li${section.level === 2 ? ' class="sub"' : ''}>
<a href="#${escape(section.id)}">
<span class="num">${escape(section.number)}</span>
<span>${escape(section.title)}</span>
<span class="leader" aria-hidden="true"></span>
<span class="page-number">${section.page}</span>
</a></li>`,
    )
    .join('')

  return `<nav class="page toc" aria-label="Contents">
<h2>Contents</h2>
<ol>${entries}</ol>
</nav>`
}

/* -------------------------------------------------------------------------- */
/* Sections                                                                    */
/* -------------------------------------------------------------------------- */

function renderSection(section: DocumentSection): string {
  const description = section.description
    ? `<p class="section-description">${escape(section.description)}</p>`
    : ''

  return `<section class="section level-${section.level}" id="${escape(section.id)}">
<h2><span class="num">${escape(section.number)}</span>${escape(section.title)}</h2>
${description}
<div class="section-body">${section.blocks.map(renderBlock).join('')}</div>
</section>`
}

function renderBlock(block: DocBlock): string {
  switch (block.type) {
    case 'heading':
      return block.level === 3
        ? `<h3 class="block">${escape(block.text)}</h3>`
        : `<h4 class="block">${escape(block.text)}</h4>`

    case 'paragraph':
      return `<p${block.variant === 'muted' ? ' class="section-description"' : ''}>${inline(block.text)}</p>`

    case 'list': {
      const tag = block.ordered ? 'ol' : 'ul'
      return `<${tag}>${block.items.map((item) => `<li>${inline(item)}</li>`).join('')}</${tag}>`
    }

    case 'fields':
      return `<dl class="fields">${block.items
        .map((item) => {
          const value = item.bullets
            ? `<ul>${item.bullets.map((bullet) => `<li>${inline(bullet)}</li>`).join('')}</ul>`
            : inline(item.value)
          return `<div><dt>${escape(item.label)}</dt><dd${item.empty ? ' class="empty"' : ''}>${value}</dd></div>`
        })
        .join('')}</dl>`

    case 'table': {
      const head = block.columns
        .map(
          (column) =>
            `<th scope="col"${column.align === 'right' ? ' class="right"' : ''}>${escape(column.header)}</th>`,
        )
        .join('')
      const body = block.rows
        .map(
          (row) =>
            `<tr>${row
              .map(
                (cell, index) =>
                  `<td${block.columns[index]?.align === 'right' ? ' class="right"' : ''}>${inline(cell)}</td>`,
              )
              .join('')}</tr>`,
        )
        .join('')
      const caption = block.caption ? `<caption>${escape(block.caption)}</caption>` : ''
      return `<figure style="margin:0">${caption}<div class="table-wrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div></figure>`
    }

    case 'callout':
      return `<aside class="callout callout-${block.tone}">
<div><p class="label">${escape(block.title ?? defaultCalloutLabel(block.tone))}</p>
<div class="content">${inline(block.text)}</div></div>
</aside>`

    case 'divider':
      return '<hr class="rule">'

    case 'pageBreak':
      return '<div style="break-before:page"></div>'

    case 'empty':
      return `<p class="empty">${escape(block.text)}</p>`
  }
}

const CALLOUT_LABELS: Record<string, string> = {
  info: 'Information',
  success: 'Success',
  warning: 'Warning',
  risk: 'Risk',
  future: 'Future scope',
}

function defaultCalloutLabel(tone: string): string {
  return CALLOUT_LABELS[tone] ?? 'Note'
}

/* -------------------------------------------------------------------------- */
/* Text                                                                        */
/* -------------------------------------------------------------------------- */

/** Newlines inside an answer become real line breaks. */
function inline(text: DocText): string {
  if (typeof text === 'string') return escape(text).replace(/\r?\n/g, '<br>')

  return toSpans(text)
    .map((span) => {
      let value = escape(span.text).replace(/\r?\n/g, '<br>')
      if (span.bold) value = `<strong>${value}</strong>`
      if (span.italic) value = `<em>${value}</em>`
      if (span.href) value = `<a href="${escape(span.href)}">${value}</a>`
      return value
    })
    .join('')
}

function escape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
