import type { DocumentMeta } from '@/types/document'

/**
 * The running footer.
 *
 * Page numbering is a property of paginated output, so on screen the footer
 * carries the page count rather than a live page number — the PDF and Word
 * exports stamp the real number on every page.
 */
export function DocumentFooter({ meta, pages }: { meta: DocumentMeta; pages: number }) {
  return (
    <footer className="flex flex-wrap items-center justify-between gap-x-6 gap-y-2 border-t border-border bg-surface px-8 py-4 text-xs text-muted-foreground sm:px-12">
      <span className="min-w-0 truncate">{meta.footerText}</span>
      <span className="flex items-center gap-4">
        <span className="tabular-nums">
          {pages} {pages === 1 ? 'page' : 'pages'}
        </span>
        <span className="tabular-nums">{meta.generatedDate}</span>
        <span>Generated by ReqStudio</span>
      </span>
    </footer>
  )
}
